#!/bin/bash
# Generate version info Swift file
# Usage: ./scripts/generate-version.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(cd "$PROJECT_DIR/../.." && pwd)"

# Read semver from repository root VERSION file (single source of truth)
SEMVER=$(cat "$REPO_ROOT/VERSION" | tr -d '\n')

# Get git commit info
cd "$PROJECT_DIR"
COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
COMMIT_FULL=$(git rev-parse HEAD 2>/dev/null || echo "unknown")

# Check if working directory is dirty
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    DIRTY=true
    COMMIT_HASH="${COMMIT_HASH}-dirty"
else
    DIRTY=false
fi

# Get build date
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate Swift file
OUTPUT_FILE="$PROJECT_DIR/BWare/Generated/Version.swift"
mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" << EOF
// Auto-generated by generate-version.sh - DO NOT EDIT
import Foundation

/// App version information
enum AppVersion {
    /// Semantic version (e.g., "0.1.0")
    static let semver = "$SEMVER"

    /// Short git commit hash (e.g., "abc1234" or "abc1234-dirty")
    static let commit = "$COMMIT_HASH"

    /// Full git commit hash
    static let commitFull = "$COMMIT_FULL"

    /// Whether the build was from a dirty working directory
    static let isDirty = $DIRTY

    /// Build date in ISO 8601 format
    static let buildDate = "$BUILD_DATE"

    /// Full version string (e.g., "0.1.0 (abc1234)")
    static var fullVersion: String {
        "\(semver) (\(commit))"
    }

    /// Display version for UI
    static var displayVersion: String {
        if isDirty {
            return "\(semver) (\(commit.replacingOccurrences(of: "-dirty", with: "")) dev)"
        }
        return "\(semver) (\(commit))"
    }
}
EOF

echo "Generated $OUTPUT_FILE"
echo "  Version: $SEMVER"
echo "  Commit:  $COMMIT_HASH"
echo "  Dirty:   $DIRTY"
